minecraft:
  image:
    repository: itzg/minecraft-server
    tag: "java16"
    pullPolicy: IfNotPresent

  minecraftServer:
    version: "1.20.1"
    eula: "TRUE"
    # Message of the Day
    motd: "Welcome to Grace's Minecraft server!"
    # A comma-separated list of player names who should be admins.
    ops: "grace"

    ## The type of Minecraft server to run, check for related settings below
    ## Common types: "VANILLA", "FABRIC", "FORGE", "SPIGOT", "BUKKIT", "PAPER",
    ## "FTBA", "SPONGEVANILLA", "AUTO_CURSEFORGE"
    ## ref: https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms
    type: "AUTO_CURSEFORGE"

    serviceType: "NodePort"
    nodePort: 30000

    autoCurseForge:
      apiKey:
        key: "$2a$10$GYahTvJRHFpImeXP3qiu8eaeESXMnh/qp9sKj3xc0tgGawk5pdKje"
      #pageUrl: "https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons"
      #pageUrl: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-11"
      pageUrl: "https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons-3"

  persistence:
    dataDir:
      enabled: true
      Size: 50Gi
